version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: dockerdave7731/reverseproxy
  backend_user:
    build:
      context: ../../udacity-db-restapi-user
    image: dockerdave7731/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-db-restapi-feed
    image: dockerdave7731/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-db-frontend
    image: dockerdave7731/udacity-frontend
